_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 400

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
# resume_from_checkpoint: "logs/experiments/runs/default/2023-01-04_16-10-02/checkpoints/last.ckpt"
