_target_: src.models.deepmtlr_model_vit.DEEP_MTLR

model: "UNETR"
dense_factor : 2 #Factor to multiply width of fc layer.
n_dense : 2   #Number of fc layers.
dropout : 0.2
C1 : 1 #Regularization term for MTLR backprop.
lr : 1e-3
weight_decay: 0.01
time_bins: 8
loss_gamma: 0.1
in_channels: 2
out_channels: 0

#CNN
k1 : 3
k2 : 5

step: 20, 50, 100, 150, 200  

#ViT
patch_xy: 80
patch_z: 80
patch_size : 8
hidden_size : 768
mlp_dim : 3072
num_layers : 8
num_heads : 12